name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: swift build -v
      
    - name: Build CLI
      run: swift build -c release --product lastfm-cli
      
    - name: Run tests
      run: swift test -v

  macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.1.app
      
    - name: Build
      run: swift build -v
      
    - name: Build CLI
      run: swift build -c release --product lastfm-cli
      
    - name: Run tests
      run: swift test -v