name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## LastFMKit ${{ github.ref_name }}
          
          ### Installation
          
          Add to your `Package.swift`:
          ```swift
          dependencies: [
              .package(url: "https://github.com/${{ github.repository }}", from: "${{ github.ref_name }}")
          ]
          ```
          
          ### Full Changelog
          https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }}